version: '3.9'

services:
  api:
    container_name: wehealthy-stg-api
    build:
      context: .
      dockerfile: Dockerfile.stg
    tty: true
    ports:
      - 2222:2222
    networks:
      - wehealthy-stg-network

networks:
  wehealthy-stg-network:
    driver: bridge
