version: '3.9'

services:
  # api:
  #   container_name: wehealthy-dev-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   tty: true
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - ./:/usr/app
  #   networks:
  #     - wehealthy-dev-network
  #   depends_on:
  #     - database

  database:
    image: postgres
    container_name: wehealthy-dev-db
    restart: always
    tty: true
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=wehealthy
    networks:
      - wehealthy-dev-network

networks:
  wehealthy-dev-network:
    driver: bridge
